# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  BUILD_VERSION: '$(build.buildNumber)'
  DOCKER_REGISTRY: '$(dockerId)/$(dockerUsername)'

steps:
- task: DotNetCoreCLI@2
  displayName: Build .Net projects
  inputs:
    command: build
    projects: 'K8SWorkshop.sln'
    arguments: --configuration $(BuildConfiguration)
    workingDirectory: '$(Build.SourcesDirectory)'

- script: sudo service docker status
  displayName: 'docker status'

- script: docker-compose -f docker-compose.yml --project-directory . build
  displayName: 'docker-compose build'

- script: |
    echo "$(dockerPassword)" | docker login  $(dockerId).azurecr.io -u $(dockerUsername) --password-stdin
    docker push $(DOCKER_REGISTRY)/k8sappone:$(BUILD_VERSION)
    docker push $(DOCKER_REGISTRY)/k8sapptwo:$(BUILD_VERSION)
  displayName: "docker publish"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactsName: 'drop'